data:
    name: 'ValidateDataset'
    images_folder: 'dataset/small'
    preprocessing:
        resize: false

front_end_model: 'Val_model_heatmap'
model:
    name: 'SuperPointNet_torch'
    params: {}
    detection_threshold: 0.005
    nms: 4
    top_k: 10000
    nn_thresh: 0.6
    pretrained: 'retrained_superpoint/models/weights/superPointNet_48000_checkpoint.pth.tar'